src/objects/Student__c.object
<CustomObject>
    <description>学生对象</description>
    <fields>
        <fullName>Education__c</fullName>
        <label>学历</label>
        <picklist>
            <picklistValues>
                <fullName>文盲</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>小学</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>初中</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>高中</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>专科</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>本科</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>硕士</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>博士</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <description>性别</description>
        <label>性别</label>
        <picklist>
            <picklistValues>
                <fullName>男</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>女</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>学生</label>
    <nameField>
        <label>学生名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StudentsBatch.cls
global with sharing class StudentsBatch implements Database.Batchable<sObject>,Database.Stateful{
    Integer queryCount = 0;
    
    String myEmailAddress = 'cherishtodaytime@163.com';
    
    global Database.QueryLocator start(database.BatchableContext bc )
    {
        String query = 'SELECT   Name,Education__c,Sex__c  FROM  Student__c';
        return Database.getQueryLocator(query);
    }
    
    global void execute (Database.BatchableContext bc, List<Student__c> students)
    {
        for(Student__c student : students) {
            student.Name='qjx'+queryCount;
            queryCount +=1;
        }
        upsert students;
    }
    
    global void finish(Database.BatchableContext bc)
    {
        /*--------execute finish----------*/
        /*注意：如果不实现Database.Stateful接口，则queryCount为0
              因为在execute执行完成便会回滚到初始状态*/
        System.debug('query count:' + queryCount);
        //send email
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(new String[]{myEmailAddress});//set mail getter
        email.setSubject('show count'); //set subject
        email.setHtmlBody('query Count:' + queryCount);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
    }
}
/*
StudentsBatch studentsBatch = new StudentsBatch();
Id batchId = Database.executeBatch(studentsBatch);
*/